version = 1
# (Default: 13) Configures the parallelism of global executor
globalExecutorParallelism = "default"

# Configuration for async io system
[asyncIO]
	# (Default: true) Whether to enable this feature
	enabled = "default"

# Configuration for threaded world generation
[threadedWorldGen]
	# (Default: true) Whether to allow feature generation (world decorations like trees, ores and etc.) run in parallel 
	# (may cause incompatibility with other mods)
	allowThreadedFeatures = "default"
	# (Default: true) Whether to allow reducing lock radius 
	# (may cause incompatibility with other mods)
	reduceLockRadius = "default"
	# (Default: true) Whether to enable this feature
	enabled = "default"

# Configuration for async scheduling system
[asyncScheduling]
	# (Default: false) (Experimental) Whether to enable this feature 
	# (may cause incompatibility with other mods)
	enabled = "default"

# Configuration for vanilla worldgen optimizations
[vanillaWorldGenOptimizations]
	# (Default: true) Whether to enable this feature 
	# (may cause incompatibility with other mods)
	enabled = "default"
	# (Default: true) Whether to enable End Biome Cache to accelerate The End worldgen 
	# This is included in lithium-fabric 
	# (may cause incompatibility with other mods) 
	useEndBiomeCache = "default"

# Configuration for general optimizations
[generalOptimizations]
	# (Default: -1) Defines which chunk compression should be used 
	# -1 for Vanilla default (also prevents mixin modifying vanilla default  
	# from being applied) 
	# 1  for GZip (RFC1952) (Vanilla compatible) 
	# 2  for Zlib (RFC1950) (Vanilla default) (Vanilla compatible) 
	# 3  for Uncompressed (Fastest, but higher disk usage) (Vanilla compatible) 
	#  
	# Original chunk data will still readable after modifying this option  
	# as this option only affects newly stored chunks 
	# Other values can result in crashes when starting minecraft  
	# to prevent further damage
	#
	chunkStreamVersion = "default"
	# (Default: true) Whether to let async chunk request no longer block server thread 
	# (may cause incompatibility with other mods) 
	optimizeAsyncChunkRequest = "default"

# Configuration for no-tick view distance
[noTickViewDistance]
	# (Default: false) Whether to use compatibility mode to send chunks 
	# This may fix some mod compatibility issues
	compatibilityMode = "default"
	# (Default: 6) No-tick view distance updates per tick 
	# Lower this for a better latency and higher this for a faster loading
	updatesPerTick = "default"
	# (Default: true) Weather to enable no-tick view distance
	enabled = "default"

# Configuration for clientside functions
[clientSide]

	# Configuration for modifying clientside max view distance
	[clientSide.modifyMaxVDConfig]
		# (Default: true) Weather to enable c2me clientside features
		enabled = "default"
		# (Default: 128) Max render distance allowed in game options
		maxViewDistance = "default"

