[extractinatorConfig]
commonItemChance = 100.0
uncommonItemChance = 50.0
rareItemChance = 25.0
veryRareItemChance = 10.0
extremelyRareItemChance = 2.0
inputCooldown = 8
outputLootMultiplier = 1.0
extractinatorRecipe = "NONE"

[extractinatorConfig.supportedMods]
minecraft_support = true
modern_industrialization_support = true
techreborn_support = true
indrev_support = true
ae2_support = true

[[extractinatorConfig.supportedBlocks]]
name = "the_extractinator:silt"
tier = "TIER_4"
yield = 75
additionalDrops = []
disabledDrops = []

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:gravel"
tier = "TIER_3"
yield = 20
disabledDrops = []

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:flint"
min = 1
max = 2
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:sand"
tier = "TIER_2"
yield = 25
disabledDrops = ["minecraft:raw_iron", "minecraft:raw_copper", "minecraft:raw_gold", "minecraft:coal", "minecraft:lapis_lazuli", "modern_industrialization:raw_tin", "modern_industrialization:lignite_coal", "modern_industrialization:silicon_dust"]

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:iron_dust"
min = 1
max = 1
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:copper_dust"
min = 1
max = 3
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:gold_dust"
min = 1
max = 1
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:coal_dust"
min = 1
max = 2
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:lazurite_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:diamond_tiny_dust"
min = 1
max = 3
rarity = "VERY_RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:emerald_tiny_dust"
min = 3
max = 9
rarity = "VERY_RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:ruby_dust"
min = 2
max = 4
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:sapphire_dust"
min = 1
max = 2
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:peridot_dust"
min = 1
max = 2
rarity = "VERY_RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:lignite_coal_dust"
min = 1
max = 3
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:silicon_dust"
min = 2
max = 4
rarity = "RARE"

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:cobblestone"
tier = "TIER_1"
yield = 10
additionalDrops = []
disabledDrops = []

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:stone"
tier = "TIER_1"
yield = 15
additionalDrops = []
disabledDrops = []

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:cobbled_deepslate"
tier = "TIER_2"
yield = 10
additionalDrops = []
disabledDrops = []

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:deepslate"
tier = "TIER_2"
yield = 15
additionalDrops = []
disabledDrops = []

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:granite"
tier = "TIER_2"
yield = 20
disabledDrops = ["modern_industrialization:uranium_dust"]

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:granite_dust"
min = 1
max = 2
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:quartz"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:uranium_dust"
min = 2
max = 4
rarity = "RARE"

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:andesite"
tier = "TIER_2"
yield = 20
disabledDrops = []

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:andesite_dust"
min = 1
max = 2
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:sodium_tiny_dust"
min = 3
max = 9
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:basalt_dust"
min = 1
max = 1
rarity = "VERY_RARE"

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:diorite"
tier = "TIER_2"
yield = 20
disabledDrops = []

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:diorite_dust"
min = 1
max = 2
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:quartz"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:tuff"
tier = "TIER_2"
yield = 25
additionalDrops = []
disabledDrops = []

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:calcite"
tier = "TIER_2"
yield = 20
disabledDrops = ["minecraft:amethyst_shard"]

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:calcite_dust"
min = 1
max = 2
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:quartz"
min = 1
max = 3
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:amethyst_shard"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:carbon_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:smooth_basalt"
tier = "TIER_3"
yield = 25
disabledDrops = ["minecraft:raw_iron", "minecraft:amethyst_shard"]

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:basalt_dust"
min = 1
max = 2
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:iron_dust"
min = 1
max = 2
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:olivine_dust"
min = 1
max = 1
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:amethyst_shard"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:netherrack"
tier = "TIER_1"
yield = 5
disabledDrops = ["minecraft:coal"]

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:netherrack_dust"
min = 2
max = 4
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:coal_dust"
min = 1
max = 1
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:sulfur_dust"
min = 1
max = 2
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:saltpeter_dust"
min = 1
max = 1
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:blackstone"
tier = "TIER_2"
yield = 25
disabledDrops = ["minecraft:coal", "techreborn:pyrite_dust"]

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:coal_dust"
min = 1
max = 1
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:sulfur_dust"
min = 1
max = 3
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:carbon_dust"
min = 1
max = 2
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:obsidian_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:pyrite_dust"
min = 2
max = 4
rarity = "RARE"

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:ancient_debris"
tier = "TIER_5"
yield = 100
disabledDrops = ["minecraft:diamond"]

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:netherite_scrap"
min = 1
max = 1
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:blaze_powder"
min = 3
max = 9
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:magma_cream"
min = 2
max = 4
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:sulfur_dust"
min = 10
max = 20
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:carbon_dust"
min = 3
max = 9
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:diamond"
min = 3
max = 9
rarity = "RARE"

[[extractinatorConfig.supportedBlocks]]
name = "minecraft:end_stone"
tier = "TIER_2"
yield = 10
disabledDrops = ["modern_industrialization:tungsten_dust", "techreborn:tungsten_small_dust", "modern_industrialization:platinum_tiny_dust", "techreborn:platinum_small_dust"]

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:endstone_dust"
min = 2
max = 4
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:tungsten_tiny_dust"
min = 1
max = 2
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:platinum_tiny_dust"
min = 1
max = 1
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:ender_pearl_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:ender_eye_dust"
min = 1
max = 3
rarity = "VERY_RARE"

[[extractinatorConfig.supportedBlocks]]
name = "blockus:marble"
tier = "TIER_2"
yield = 20
disabledDrops = []

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:marble_dust"
min = 1
max = 2
rarity = "COMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:calcite_dust"
min = 1
max = 1
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:obsidian_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:carbon_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks]]
name = "blockus:bluestone"
tier = "TIER_1"
yield = 20
disabledDrops = []

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:blue_dye"
min = 1
max = 1
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:lazurite_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:sapphire_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:sodalite_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:sulfur_dust"
min = 1
max = 3
rarity = "RARE"

[[extractinatorConfig.supportedBlocks]]
name = "blockus:limestone"
tier = "TIER_2"
yield = 20
disabledDrops = ["minecraft:raw_iron", "techreborn:pyrite_dust"]

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:iron_dust"
min = 1
max = 2
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:calcite_dust"
min = 1
max = 2
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:quartz"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:pyrite_dust"
min = 2
max = 4
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:carbon_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks]]
name = "promenade:carbonite"
tier = "TIER_2"
yield = 25
disabledDrops = ["minecraft:coal"]

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:coal_dust"
min = 1
max = 2
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:carbon_dust"
min = 1
max = 3
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks]]
name = "promenade:blunite"
tier = "TIER_1"
yield = 20
disabledDrops = []

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "minecraft:blue_dye"
min = 1
max = 1
rarity = "UNCOMMON"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:lazurite_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:sapphire_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "techreborn:sodalite_dust"
min = 1
max = 1
rarity = "RARE"

[[extractinatorConfig.supportedBlocks.additionalDrops]]
name = "modern_industrialization:sulfur_dust"
min = 1
max = 3
rarity = "RARE"
[worldConfig]
generateSiltOre = true
siltVeinSize = 12
siltVeinsPerChunk = 8
siltMaxSpawnHeight = 24
generateCabins = true
cabinSpacing = 9
cabinSeparation = 5
cabinMinHeight = 0
cabinMaxHeight = 30
deepslateCabinMinHeight = -48
deepslateCabinMaxHeight = -1
intactCabinWeight = 1
brokenCabinWeight = 2
moddedLootInChests = true
